spring:
  application:
    name: ESP-Doorbell

  config:
    import: optional:application-${spring.profiles.active}.yaml

  jackson:
    time-zone: UTC

  http:
    codecs:
      max-in-memory-size: 16MB

server:
  forward-headers-strategy: framework

streaming:
  websocket-base-url: wss://doorbell-thomas.site
  gstreamer:
    video-bitrate: 1M
    audio-bitrate: 128k
    cpu-used: 5
    opus-frame-size-ms: 20
    keyframe-max-dist: 30

app:
  storage:
    upload-dir: uploads
  api:
    base-url: https://doorbell-thomas.site
