spring:
  application:
    name: ESP-Doorbell

  config:
    import: optional:application-${spring.profiles.active}.yaml

  jackson:
    time-zone: UTC

  http:
    codecs:
      max-in-memory-size: 16MB

server:
  forward-headers-strategy: framework

app:
  ice:
    turn-host: ${TURN_SERVER_HOST}
    turn-port: ${TURN_SERVER_PORT}
    turn-username: ${TURN_USERNAME}
    turn-password: ${TURN_PASSWORD}
  storage:
    upload-dir: uploads
  api:
    base-url: https://doorbell-thomas.site
