spring:
  application:
    name: ESP-Doorbell

  config:
    import: secrets.yaml

  jackson:
    time-zone: UTC

streaming:
  websocket-base-url: ws://localhost:8080
  ffmpeg:
    path: ffmpeg
    video-bitrate: 1M
    audio-bitrate: 128k
    cluster-time-ms: 500
  tcp:
    video-port: 5001
    audio-port: 5002
  sync:
    max-sync-wait-ms: 500
    max-queue-size: 100
