spring:
  application:
    name: ESP-Doorbell

  config:
    import: secrets.yaml

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate.jdbc.time_zone: UTC+07:00

    open-in-view: true

  jackson:
    time-zone: UTC



