spring:
  application:
    name: ESP-Doorbell

  config:
    import: optional:application-${spring.profiles.active}.yaml

  jackson:
    time-zone: UTC

server:
  forward-headers-strategy: framework

streaming:
  websocket-base-url: wss://doorbell-thomas.site
  ffmpeg:
    path: ffmpeg
    video-bitrate: 1M
    audio-bitrate: 128k
    cluster-time-ms: 500
  tcp:
    video-port: 5001
    audio-port: 5002
  sync:
    max-sync-wait-ms: 500
    max-queue-size: 100
